api_film_create:
    path:     /api/film/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Api\Controller\CreateFilmController::executeAction }
    methods: [POST]

api_film_update:
    path:     /api/film/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Api\Controller\UpdateFilmController::executeAction }
    methods: [PUT]

api_film_delete:
    path:     /api/film/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Api\Controller\DeleteFilmController::executeAction }
    methods: [DELETE]

api_film_list:
    path:     /api/film/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Api\Controller\ListFilmsController::executeAction }
    methods: [GET]

film_details:
    path:     /film/list/{filmId}/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Controller\ListFilmDetailsController::executeAction }
    methods: [GET]
    requirements:
        filmId: '\d+'

film_list:
    path:     /film/list/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Controller\ListFilmsController::executeAction }
    methods: [GET]

film_test:
    path:     /film/test_default_controller/
    defaults: { _controller: Bundle\FilmBundle\Infrastructure\http\Controller\DefaultController::indexAction }
