actor:
    resource: "@ActorBundle/Resources/config/routing.yml"
    prefix:   /actor

film:
    resource: "@FilmBundle/Resources/config/routing.yml"
    prefix:   /film

app:
    resource: '@AppBundle/Controller/'
    type: annotation
