actor:
    resource: "@ActorBundle/Resources/config/routing.yml"
    prefix:   /

film:
    resource: "@FilmBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
