api_actor_create:
    path:     /api/actor/
    defaults: { _controller: actor.controller.api.create_actor:executeAction }
    methods: [POST]

api_actor_update:
    path:     /api/actor/
    defaults: { _controller: actor.controller.api.update_actor:executeAction }
    methods: [PUT]

api_actor_delete:
    path:     /api/actor/
    defaults: { _controller: actor.controller.api.delete_actor:executeAction }
    methods: [DELETE]

api_actor_list:
    path:     /api/actor/
    defaults: { _controller: actor.controller.api.list_actors:executeAction }
    methods: [GET]

actor_details:
    path:     /actor/list/{actorId}/
    defaults: { _controller: actor.controller.list_sctor_details:executeAction }
    methods: [GET]
    requirements:
        actorId: '\d+'

actor_list:
    path:     /actor/list/
    defaults: { _controller: actor.controller.list_actors:executeAction }
    methods: [GET]

actor_test:
    path:     /actor/test_default_controller/
    defaults: { _controller: Bundle\ActorBundle\Infrastructure\http\Controller\DefaultController::indexAction }
