<?php

namespace Bundle\FilmBundle\Infrastructure\Repository;

use Bundle\FilmBundle\Domain\Entity\Film;
use Bundle\FilmBundle\Domain\Interfaces\FilmRepository;
use Psr\Cache\CacheItemPoolInterface;


/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CachedFilmRepository extends \Doctrine\ORM\EntityRepository implements \Bundle\FilmBundle\Domain\Interfaces\FilmRepository
{
    private $filmRepository;
    private $cache;



    public function __construct(
        FilmRepository $filmRepository,
        CacheItemPoolInterface $cache
    )
    {
        $this->filmRepository = $filmRepository;
        $this->cache = $cache;
    }

    public function findAllOrderedByName()
    {
        return $this->filmRepository->findAllOrderedByName();
    }

    public function findOneById(int $id): Film
    {
        $item = $this->cache->getItem((string) $id);

        if (!$item->isHit()) {
            $film = $this->filmRepository->findOneById($id);

            $item->set($film);
            $this->cache->save($item);
        }

        return $item->get();
    }

    public function save(Film $film): void
    {
        $this->filmRepository->save($film);
        $this->cache->clear();
    }

    public function delete(Film $film): void
    {
        $this->filmRepository->delete($film);
        $this->cache->clear();
    }

}
