<?php

namespace Bundle\FilmBundle\Infrastructure\Repository;

use Bundle\FilmBundle\Domain\Entity\Film;
use Doctrine\ORM\EntityManagerInterface;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository implements \Bundle\FilmBundle\Domain\Interfaces\FilmRepository
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function findAllOrderedByName()
    {
        return $this->entityManager
            ->createQuery(
                'SELECT f FROM FilmBundle:Film f ORDER BY f.name ASC'
            )
            ->getResult();
    }

    public function findOneById(int $id): Film
    {
        return $this->entityManager
            ->createQuery(
                'SELECT f FROM FilmBundle:Film f WHERE f.id = :id'
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function save(Film $film): void
    {
        $this->entityManager->persist($film);
        $this->entityManager->flush();
    }

    public function delete(Film $film): void
    {
        $this->entityManager->remove($film);
        $this->entityManager->flush();
    }

}
