<?php

namespace Bundle\ActorBundle\Infraestructure\Repository;

use Bundle\ActorBundle\Entity\Actor;
use Doctrine\ORM\EntityManagerInterface;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends \Doctrine\ORM\EntityRepository
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function findAllOrderedByName()
    {
        return $this->entityManager
            ->createQuery(
                'SELECT a FROM ActorBundle:Actor a ORDER BY a.name ASC'
            )
            ->getResult();
    }

    public function findOneById(int $id)
    {
        return $this->entityManager
            ->createQuery(
                'SELECT a FROM ActorBundle:Actor a WHERE a.id = :id'
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

    public function saveActor(Actor $actor)
    {
        $this->entityManager->persist($actor);
        $this->entityManager->flush();
    }
}
