Bundle\ActorBundle\Entity\Actor:
    type: entity
    table: actor
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '80'
            unique: true
    manyToMany:
        films:
            targetEntity: Bundle\FilmBundle\Entity\Film
            mappedBy: actors

    repositoryClass: Bundle\ActorBundle\Infrastructure\Repository\ActorRepository

    lifecycleCallbacks: {  }
