Bundle\ActorBundle\Entity\Actor:
    type: entity
    OneToMany:
        film:
            targetEntity: \Bundle\FilmBundle\Entity\Film
            inversedBy: actor
    table: actor
    repositoryClass: Bundle\ActorBundle\Infraestructure\Repository\ActorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '80'
            unique: true
    lifecycleCallbacks: {  }
